Adding support for relation-broken event
canonical/sdcore-nrf-operator pull request #27
Opened 2023-06-23 12:51 UTC by Gmerold

# Description

- Adds new, custom `nrf_broken` event to enable support for `relation-broken` in SD-Core charms

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

2023-06-23 13:01 UTC, gruyaume requested changes

2023-06-23 13:01 UTC, gruyaume commented on lib/charms/sdcore_nrf/v0/fiveg_nrf.py
IMO there is not reason in updating the lib, we could simply have the following in each of the charms requiring NRF:

```python
self.framework.observe(self.on.nrf_relation_broken, self._on_nrf_broken)
```

2023-06-27 14:03 UTC, Gmerold commented on lib/charms/sdcore_nrf/v0/fiveg_nrf.py
Yes, I saw this one coming :)
As we already discussed during the daily, while working with the Observability team, I've learnt that there's a convention saying that if we have a lib for something, everything related to this _something_ should be handled within the library. 
Having that said, I don't mind going against this convention, although personally I think it's a bit cleaner to use the library.
Let's agree on one, common approach. 

@ghislainbourgeois, @saltiyazan, @sanchezfdezjavier WDYT?

2023-06-30 17:53 UTC, gruyaume approved these changes

2023-07-03 06:54 UTC, saltiyazan commented on tests/unit/charms/sdcore_nrf/v0/dummy_requirer_charm/src/dummy_requirer_charm.py
> +        logging.info(f"Received {event}")
Are we not doing anything to handle the event?

2023-07-03 06:54 UTC, saltiyazan commented on tests/unit/charms/sdcore_nrf/v0/dummy_requirer_charm/src/dummy_requirer_charm.py
> +        logging.info(f"Received {event}")
Never mind, I'm looking at the wrong file :)

2023-07-03 06:57 UTC, saltiyazan commented on lib/charms/sdcore_nrf/v0/fiveg_nrf.py
On my side I don't have problems with following this convention, it is cleaner, although it might be a little bit of an overkill in this case where we just would block the charm when relation is broken.
I don't insist on changing it.

2023-07-03 06:57 UTC, saltiyazan approved these changes

2023-08-31 07:05 UTC, merged